# Generated by Django 4.0.3 on 2022-03-12 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedback',
            old_name='Phone_Number',
            new_name='Mobile_Number',
        ),
        migrations.AlterField(
            model_name='feedback',
            name='feedback',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterModelTable(
            name='feedback',
            table='Customer_FeedBack',
        ),
    ]
